### PR TITLE
Default to 7.11

### PR DESCRIPTION
**Pull request by jsanz**
Change in the CI job to deploy 7.11 in the root of <https://maps.elastic.co>

### CODE REVIEW

**Review by nickpeihl — APPROVED** [review]
lgtm, but let's wait until closer to the 7.11 release date to merge. That way we can still deploy changes (such as bugfixes) between now and then without deploying 7.11 in the root page.

**Comment by jsanz** [comment]
OK so we will wait for this then a few weeks. You may have to merge this if I'm not around :slightly_smiling_face: 

FYI, I've run the CI job to deploy the branch in staging and it's available at

https://maps-staging.elastic.co/v7.11

**Comment by jsanz** [comment]
Also in production :tada: 

https://maps.elastic.co/v7.11/

**Comment by nickpeihl** [comment]
Oops. This was done in #308

**Pull request closed without merging**
