### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by jsanz**
Upgrades of:

* `html-webpack-plugin`
* `resolve-url-loader`
* `webpack`
* `webpack-dev-server`
* `mapboxgl`
* `ws` (directly in `yarn.lock`
* `postcss` (directly in `yarn.lock`

Replaced the deprecated `webapp-webpack-plugin` by `favicons-webpack-plugin`.

This PR should address a few of the security issues but not all of them. A major upgrade of Webpack and probably other components should also be considered at some point.

### CODE REVIEW

**Comment by jsanz** [comment]
@nickpeihl I think this should be OK to test, I bumped a few dependencies based on the Github vulnerability report. As usual, quite a few vulnerabilities are present in transient dependencies so I did my best to upgrade the direct dependencies (where it seemed safe).

**Review by nickpeihl — APPROVED** [review]
lgtm. Tested in Firefox and saw no issues.

Since we're bundling this repo with Elastic Maps Server, I think we can limit the backport to versions >=7.13 now. Older releases probably don't need non-critical updates.

**Comment by jsanz** [comment]
Sorry, one more commit f5f0a91, inspired by [how EUI handles the `trim` security issue](https://github.com/elastic/eui/blob/3e4beebbd7d2f549589e5fb8c03a197afd5cebbc/package.json#L45-L47) I used the same approach to force the upgrade of our vulnerable packages.

I also passed the code through Snyk CLI tool (we may consider change dependabot by Snyk in the future) and now it's not reporting any security issues.

**Review by nickpeihl — APPROVED** [review]
lgtm

**Pull request merged**
